new PlayerText:LaptopBackground[MAX_PLAYERS];
new PlayerText:LaptopMonitor[MAX_PLAYERS];
new PlayerText:LaptopMonitorLine[MAX_PLAYERS];
new PlayerText:LaptopVersion[MAX_PLAYERS];
new PlayerText:LaptopCamera[MAX_PLAYERS];
new PlayerText:WarehouseButton[MAX_PLAYERS];
new PlayerText:EBankButton[MAX_PLAYERS];
new PlayerText:AdsListButton[MAX_PLAYERS];
new PlayerText:SpeedTunerButton[MAX_PLAYERS];
new PlayerText:YellowPageButton[MAX_PLAYERS];
new PlayerText:WarehouseIcon[MAX_PLAYERS];
new PlayerText:EBankIcon[MAX_PLAYERS];
new PlayerText:AdsListIcon[MAX_PLAYERS];
new PlayerText:SpeedTunerIcon[MAX_PLAYERS];
new PlayerText:YellowPageIcon[MAX_PLAYERS];
new PlayerText:VehicleImportButton[MAX_PLAYERS];
new PlayerText:FactionImportButton[MAX_PLAYERS];
new PlayerText:FactionImportIcon[MAX_PLAYERS];
new PlayerText:VehicleImportIcon[MAX_PLAYERS];
new PlayerText:LaptopCloseButton[MAX_PLAYERS];

CreateLaptopDraw(playerid)
{
	LaptopBackground[playerid] = CreatePlayerTextDraw(playerid, 323.000000, 130.000000, "_");
	PlayerTextDrawFont(playerid, LaptopBackground[playerid], 1);
	PlayerTextDrawLetterSize(playerid, LaptopBackground[playerid], 0.600000, 25.749988);
	PlayerTextDrawTextSize(playerid, LaptopBackground[playerid], 298.500000, 340.000000);
	PlayerTextDrawSetOutline(playerid, LaptopBackground[playerid], 1);
	PlayerTextDrawSetShadow(playerid, LaptopBackground[playerid], 0);
	PlayerTextDrawAlignment(playerid, LaptopBackground[playerid], 2);
	PlayerTextDrawColor(playerid, LaptopBackground[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, LaptopBackground[playerid], 255);
	PlayerTextDrawBoxColor(playerid, LaptopBackground[playerid], 255);
	PlayerTextDrawUseBox(playerid, LaptopBackground[playerid], 1);
	PlayerTextDrawSetProportional(playerid, LaptopBackground[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, LaptopBackground[playerid], 0);

	LaptopMonitor[playerid] = CreatePlayerTextDraw(playerid, 323.000000, 146.000000, "_");
	PlayerTextDrawFont(playerid, LaptopMonitor[playerid], 1);
	PlayerTextDrawLetterSize(playerid, LaptopMonitor[playerid], 0.600000, 21.400054);
	PlayerTextDrawTextSize(playerid, LaptopMonitor[playerid], 298.500000, 332.000000);
	PlayerTextDrawSetOutline(playerid, LaptopMonitor[playerid], 1);
	PlayerTextDrawSetShadow(playerid, LaptopMonitor[playerid], 0);
	PlayerTextDrawAlignment(playerid, LaptopMonitor[playerid], 2);
	PlayerTextDrawColor(playerid, LaptopMonitor[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, LaptopMonitor[playerid], 255);
	PlayerTextDrawBoxColor(playerid, LaptopMonitor[playerid], -1);
	PlayerTextDrawUseBox(playerid, LaptopMonitor[playerid], 1);
	PlayerTextDrawSetProportional(playerid, LaptopMonitor[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, LaptopMonitor[playerid], 0);

	LaptopMonitorLine[playerid] = CreatePlayerTextDraw(playerid, 323.000000, 220.000000, "_");
	PlayerTextDrawFont(playerid, LaptopMonitorLine[playerid], 1);
	PlayerTextDrawLetterSize(playerid, LaptopMonitorLine[playerid], 0.600000, 0.050000);
	PlayerTextDrawTextSize(playerid, LaptopMonitorLine[playerid], 298.500000, 329.000000);
	PlayerTextDrawSetOutline(playerid, LaptopMonitorLine[playerid], 1);
	PlayerTextDrawSetShadow(playerid, LaptopMonitorLine[playerid], 0);
	PlayerTextDrawAlignment(playerid, LaptopMonitorLine[playerid], 2);
	PlayerTextDrawColor(playerid, LaptopMonitorLine[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, LaptopMonitorLine[playerid], 255);
	PlayerTextDrawBoxColor(playerid, LaptopMonitorLine[playerid], 135);
	PlayerTextDrawUseBox(playerid, LaptopMonitorLine[playerid], 1);
	PlayerTextDrawSetProportional(playerid, LaptopMonitorLine[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, LaptopMonitorLine[playerid], 0);

	LaptopVersion[playerid] = CreatePlayerTextDraw(playerid, 300.000000, 345.000000, "U-Pro");
	PlayerTextDrawFont(playerid, LaptopVersion[playerid], 1);
	PlayerTextDrawLetterSize(playerid, LaptopVersion[playerid], 0.437500, 1.299998);
	PlayerTextDrawTextSize(playerid, LaptopVersion[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, LaptopVersion[playerid], 1);
	PlayerTextDrawSetShadow(playerid, LaptopVersion[playerid], 0);
	PlayerTextDrawAlignment(playerid, LaptopVersion[playerid], 1);
	PlayerTextDrawColor(playerid, LaptopVersion[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, LaptopVersion[playerid], 255);
	PlayerTextDrawBoxColor(playerid, LaptopVersion[playerid], 50);
	PlayerTextDrawUseBox(playerid, LaptopVersion[playerid], 0);
	PlayerTextDrawSetProportional(playerid, LaptopVersion[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, LaptopVersion[playerid], 0);

	LaptopCamera[playerid] = CreatePlayerTextDraw(playerid, 315.000000, 130.000000, "HUD:radar_datedisco");
	PlayerTextDrawFont(playerid, LaptopCamera[playerid], 4);
	PlayerTextDrawLetterSize(playerid, LaptopCamera[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, LaptopCamera[playerid], 12.500000, 12.000000);
	PlayerTextDrawSetOutline(playerid, LaptopCamera[playerid], 1);
	PlayerTextDrawSetShadow(playerid, LaptopCamera[playerid], 0);
	PlayerTextDrawAlignment(playerid, LaptopCamera[playerid], 1);
	PlayerTextDrawColor(playerid, LaptopCamera[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, LaptopCamera[playerid], 255);
	PlayerTextDrawBoxColor(playerid, LaptopCamera[playerid], 50);
	PlayerTextDrawUseBox(playerid, LaptopCamera[playerid], 1);
	PlayerTextDrawSetProportional(playerid, LaptopCamera[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, LaptopCamera[playerid], 1);

	WarehouseButton[playerid] = CreatePlayerTextDraw(playerid, 188.000000, 165.000000, "WAREHOUSE");
	PlayerTextDrawFont(playerid, WarehouseButton[playerid], 2);
	PlayerTextDrawLetterSize(playerid, WarehouseButton[playerid], 0.183329, 1.100000);
	PlayerTextDrawTextSize(playerid, WarehouseButton[playerid], 16.500000, 55.000000);
	PlayerTextDrawSetOutline(playerid, WarehouseButton[playerid], 1);
	PlayerTextDrawSetShadow(playerid, WarehouseButton[playerid], 0);
	PlayerTextDrawAlignment(playerid, WarehouseButton[playerid], 2);
	PlayerTextDrawColor(playerid, WarehouseButton[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, WarehouseButton[playerid], 255);
	PlayerTextDrawBoxColor(playerid, WarehouseButton[playerid], 200);
	PlayerTextDrawUseBox(playerid, WarehouseButton[playerid], 1);
	PlayerTextDrawSetProportional(playerid, WarehouseButton[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, WarehouseButton[playerid], 1);

	EBankButton[playerid] = CreatePlayerTextDraw(playerid, 251.000000, 165.000000, "E-BANKING");
	PlayerTextDrawFont(playerid, EBankButton[playerid], 2);
	PlayerTextDrawLetterSize(playerid, EBankButton[playerid], 0.183329, 1.100000);
	PlayerTextDrawTextSize(playerid, EBankButton[playerid], 16.500000, 55.000000);
	PlayerTextDrawSetOutline(playerid, EBankButton[playerid], 1);
	PlayerTextDrawSetShadow(playerid, EBankButton[playerid], 0);
	PlayerTextDrawAlignment(playerid, EBankButton[playerid], 2);
	PlayerTextDrawColor(playerid, EBankButton[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, EBankButton[playerid], 255);
	PlayerTextDrawBoxColor(playerid, EBankButton[playerid], 200);
	PlayerTextDrawUseBox(playerid, EBankButton[playerid], 1);
	PlayerTextDrawSetProportional(playerid, EBankButton[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, EBankButton[playerid], 1);

	AdsListButton[playerid] = CreatePlayerTextDraw(playerid, 315.000000, 165.000000, "Ads List");
	PlayerTextDrawFont(playerid, AdsListButton[playerid], 2);
	PlayerTextDrawLetterSize(playerid, AdsListButton[playerid], 0.183329, 1.100000);
	PlayerTextDrawTextSize(playerid, AdsListButton[playerid], 16.500000, 55.000000);
	PlayerTextDrawSetOutline(playerid, AdsListButton[playerid], 1);
	PlayerTextDrawSetShadow(playerid, AdsListButton[playerid], 0);
	PlayerTextDrawAlignment(playerid, AdsListButton[playerid], 2);
	PlayerTextDrawColor(playerid, AdsListButton[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, AdsListButton[playerid], 255);
	PlayerTextDrawBoxColor(playerid, AdsListButton[playerid], 200);
	PlayerTextDrawUseBox(playerid, AdsListButton[playerid], 1);
	PlayerTextDrawSetProportional(playerid, AdsListButton[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, AdsListButton[playerid], 1);

	SpeedTunerButton[playerid] = CreatePlayerTextDraw(playerid, 381.000000, 165.000000, "V-Speed Tuner");
	PlayerTextDrawFont(playerid, SpeedTunerButton[playerid], 2);
	PlayerTextDrawLetterSize(playerid, SpeedTunerButton[playerid], 0.183329, 1.100000);
	PlayerTextDrawTextSize(playerid, SpeedTunerButton[playerid], 16.500000, 60.500000);
	PlayerTextDrawSetOutline(playerid, SpeedTunerButton[playerid], 1);
	PlayerTextDrawSetShadow(playerid, SpeedTunerButton[playerid], 0);
	PlayerTextDrawAlignment(playerid, SpeedTunerButton[playerid], 2);
	PlayerTextDrawColor(playerid, SpeedTunerButton[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, SpeedTunerButton[playerid], 255);
	PlayerTextDrawBoxColor(playerid, SpeedTunerButton[playerid], 200);
	PlayerTextDrawUseBox(playerid, SpeedTunerButton[playerid], 1);
	PlayerTextDrawSetProportional(playerid, SpeedTunerButton[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, SpeedTunerButton[playerid], 1);

	YellowPageButton[playerid] = CreatePlayerTextDraw(playerid, 450.000000, 165.000000, "Yellow Page");
	PlayerTextDrawFont(playerid, YellowPageButton[playerid], 2);
	PlayerTextDrawLetterSize(playerid, YellowPageButton[playerid], 0.183329, 1.100000);
	PlayerTextDrawTextSize(playerid, YellowPageButton[playerid], 16.500000, 60.500000);
	PlayerTextDrawSetOutline(playerid, YellowPageButton[playerid], 1);
	PlayerTextDrawSetShadow(playerid, YellowPageButton[playerid], 0);
	PlayerTextDrawAlignment(playerid, YellowPageButton[playerid], 2);
	PlayerTextDrawColor(playerid, YellowPageButton[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, YellowPageButton[playerid], 255);
	PlayerTextDrawBoxColor(playerid, YellowPageButton[playerid], 200);
	PlayerTextDrawUseBox(playerid, YellowPageButton[playerid], 1);
	PlayerTextDrawSetProportional(playerid, YellowPageButton[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, YellowPageButton[playerid], 1);

	WarehouseIcon[playerid] = CreatePlayerTextDraw(playerid, 177.000000, 144.000000, "HUD:radar_propertyg");
	PlayerTextDrawFont(playerid, WarehouseIcon[playerid], 4);
	PlayerTextDrawLetterSize(playerid, WarehouseIcon[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, WarehouseIcon[playerid], 19.000000, 19.500000);
	PlayerTextDrawSetOutline(playerid, WarehouseIcon[playerid], 1);
	PlayerTextDrawSetShadow(playerid, WarehouseIcon[playerid], 0);
	PlayerTextDrawAlignment(playerid, WarehouseIcon[playerid], 1);
	PlayerTextDrawColor(playerid, WarehouseIcon[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, WarehouseIcon[playerid], 255);
	PlayerTextDrawBoxColor(playerid, WarehouseIcon[playerid], 50);
	PlayerTextDrawUseBox(playerid, WarehouseIcon[playerid], 1);
	PlayerTextDrawSetProportional(playerid, WarehouseIcon[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, WarehouseIcon[playerid], 0);

	EBankIcon[playerid] = CreatePlayerTextDraw(playerid, 243.000000, 146.000000, "HUD:radar_cash");
	PlayerTextDrawFont(playerid, EBankIcon[playerid], 4);
	PlayerTextDrawLetterSize(playerid, EBankIcon[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, EBankIcon[playerid], 15.500000, 16.000000);
	PlayerTextDrawSetOutline(playerid, EBankIcon[playerid], 1);
	PlayerTextDrawSetShadow(playerid, EBankIcon[playerid], 0);
	PlayerTextDrawAlignment(playerid, EBankIcon[playerid], 1);
	PlayerTextDrawColor(playerid, EBankIcon[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, EBankIcon[playerid], 255);
	PlayerTextDrawBoxColor(playerid, EBankIcon[playerid], 50);
	PlayerTextDrawUseBox(playerid, EBankIcon[playerid], 1);
	PlayerTextDrawSetProportional(playerid, EBankIcon[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, EBankIcon[playerid], 0);

	AdsListIcon[playerid] = CreatePlayerTextDraw(playerid, 306.000000, 146.000000, "HUD:radar_gangb");
	PlayerTextDrawFont(playerid, AdsListIcon[playerid], 4);
	PlayerTextDrawLetterSize(playerid, AdsListIcon[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, AdsListIcon[playerid], 15.500000, 16.000000);
	PlayerTextDrawSetOutline(playerid, AdsListIcon[playerid], 1);
	PlayerTextDrawSetShadow(playerid, AdsListIcon[playerid], 0);
	PlayerTextDrawAlignment(playerid, AdsListIcon[playerid], 1);
	PlayerTextDrawColor(playerid, AdsListIcon[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, AdsListIcon[playerid], 255);
	PlayerTextDrawBoxColor(playerid, AdsListIcon[playerid], 50);
	PlayerTextDrawUseBox(playerid, AdsListIcon[playerid], 1);
	PlayerTextDrawSetProportional(playerid, AdsListIcon[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, AdsListIcon[playerid], 0);

	SpeedTunerIcon[playerid] = CreatePlayerTextDraw(playerid, 371.000000, 146.000000, "HUD:radar_impound");
	PlayerTextDrawFont(playerid, SpeedTunerIcon[playerid], 4);
	PlayerTextDrawLetterSize(playerid, SpeedTunerIcon[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, SpeedTunerIcon[playerid], 15.500000, 16.000000);
	PlayerTextDrawSetOutline(playerid, SpeedTunerIcon[playerid], 1);
	PlayerTextDrawSetShadow(playerid, SpeedTunerIcon[playerid], 0);
	PlayerTextDrawAlignment(playerid, SpeedTunerIcon[playerid], 1);
	PlayerTextDrawColor(playerid, SpeedTunerIcon[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, SpeedTunerIcon[playerid], 255);
	PlayerTextDrawBoxColor(playerid, SpeedTunerIcon[playerid], 50);
	PlayerTextDrawUseBox(playerid, SpeedTunerIcon[playerid], 1);
	PlayerTextDrawSetProportional(playerid, SpeedTunerIcon[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, SpeedTunerIcon[playerid], 0);

	YellowPageIcon[playerid] = CreatePlayerTextDraw(playerid, 441.000000, 146.000000, "HUD:radar_cesarviapando");
	PlayerTextDrawFont(playerid, YellowPageIcon[playerid], 4);
	PlayerTextDrawLetterSize(playerid, YellowPageIcon[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, YellowPageIcon[playerid], 15.500000, 16.000000);
	PlayerTextDrawSetOutline(playerid, YellowPageIcon[playerid], 1);
	PlayerTextDrawSetShadow(playerid, YellowPageIcon[playerid], 0);
	PlayerTextDrawAlignment(playerid, YellowPageIcon[playerid], 1);
	PlayerTextDrawColor(playerid, YellowPageIcon[playerid], -65281);
	PlayerTextDrawBackgroundColor(playerid, YellowPageIcon[playerid], 255);
	PlayerTextDrawBoxColor(playerid, YellowPageIcon[playerid], 50);
	PlayerTextDrawUseBox(playerid, YellowPageIcon[playerid], 1);
	PlayerTextDrawSetProportional(playerid, YellowPageIcon[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, YellowPageIcon[playerid], 0);

	VehicleImportButton[playerid] = CreatePlayerTextDraw(playerid, 192.000000, 202.000000, "VEHICLE IMPORT");
	PlayerTextDrawFont(playerid, VehicleImportButton[playerid], 2);
	PlayerTextDrawLetterSize(playerid, VehicleImportButton[playerid], 0.183329, 1.100000);
	PlayerTextDrawTextSize(playerid, VehicleImportButton[playerid], 16.500000, 63.500000);
	PlayerTextDrawSetOutline(playerid, VehicleImportButton[playerid], 1);
	PlayerTextDrawSetShadow(playerid, VehicleImportButton[playerid], 0);
	PlayerTextDrawAlignment(playerid, VehicleImportButton[playerid], 2);
	PlayerTextDrawColor(playerid, VehicleImportButton[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, VehicleImportButton[playerid], 255);
	PlayerTextDrawBoxColor(playerid, VehicleImportButton[playerid], 200);
	PlayerTextDrawUseBox(playerid, VehicleImportButton[playerid], 1);
	PlayerTextDrawSetProportional(playerid, VehicleImportButton[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, VehicleImportButton[playerid], 1);

	FactionImportButton[playerid] = CreatePlayerTextDraw(playerid, 264.000000, 202.000000, "UNKNOWN");
	PlayerTextDrawFont(playerid, FactionImportButton[playerid], 2);
	PlayerTextDrawLetterSize(playerid, FactionImportButton[playerid], 0.183329, 1.100000);
	PlayerTextDrawTextSize(playerid, FactionImportButton[playerid], 16.500000, 63.500000);
	PlayerTextDrawSetOutline(playerid, FactionImportButton[playerid], 1);
	PlayerTextDrawSetShadow(playerid, FactionImportButton[playerid], 0);
	PlayerTextDrawAlignment(playerid, FactionImportButton[playerid], 2);
	PlayerTextDrawColor(playerid, FactionImportButton[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, FactionImportButton[playerid], 255);
	PlayerTextDrawBoxColor(playerid, FactionImportButton[playerid], 200);
	PlayerTextDrawUseBox(playerid, FactionImportButton[playerid], 1);
	PlayerTextDrawSetProportional(playerid, FactionImportButton[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, FactionImportButton[playerid], 1);

	FactionImportIcon[playerid] = CreatePlayerTextDraw(playerid, 255.000000, 184.000000, "HUD:radar_airyard");
	PlayerTextDrawFont(playerid, FactionImportIcon[playerid], 4);
	PlayerTextDrawLetterSize(playerid, FactionImportIcon[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, FactionImportIcon[playerid], 14.500000, 13.500000);
	PlayerTextDrawSetOutline(playerid, FactionImportIcon[playerid], 1);
	PlayerTextDrawSetShadow(playerid, FactionImportIcon[playerid], 0);
	PlayerTextDrawAlignment(playerid, FactionImportIcon[playerid], 1);
	PlayerTextDrawColor(playerid, FactionImportIcon[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, FactionImportIcon[playerid], 255);
	PlayerTextDrawBoxColor(playerid, FactionImportIcon[playerid], 50);
	PlayerTextDrawUseBox(playerid, FactionImportIcon[playerid], 1);
	PlayerTextDrawSetProportional(playerid, FactionImportIcon[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, FactionImportIcon[playerid], 0);

	VehicleImportIcon[playerid] = CreatePlayerTextDraw(playerid, 184.000000, 182.000000, "HUD:radar_impound");
	PlayerTextDrawFont(playerid, VehicleImportIcon[playerid], 4);
	PlayerTextDrawLetterSize(playerid, VehicleImportIcon[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, VehicleImportIcon[playerid], 15.500000, 16.000000);
	PlayerTextDrawSetOutline(playerid, VehicleImportIcon[playerid], 1);
	PlayerTextDrawSetShadow(playerid, VehicleImportIcon[playerid], 0);
	PlayerTextDrawAlignment(playerid, VehicleImportIcon[playerid], 1);
	PlayerTextDrawColor(playerid, VehicleImportIcon[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, VehicleImportIcon[playerid], 255);
	PlayerTextDrawBoxColor(playerid, VehicleImportIcon[playerid], 50);
	PlayerTextDrawUseBox(playerid, VehicleImportIcon[playerid], 1);
	PlayerTextDrawSetProportional(playerid, VehicleImportIcon[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, VehicleImportIcon[playerid], 0);

	LaptopCloseButton[playerid] = CreatePlayerTextDraw(playerid, 485.000000, 132.000000, "X");
	PlayerTextDrawFont(playerid, LaptopCloseButton[playerid], 2);
	PlayerTextDrawLetterSize(playerid, LaptopCloseButton[playerid], 0.258332, 0.949999);
	PlayerTextDrawTextSize(playerid, LaptopCloseButton[playerid], 16.500000, 9.000000);
	PlayerTextDrawSetOutline(playerid, LaptopCloseButton[playerid], 1);
	PlayerTextDrawSetShadow(playerid, LaptopCloseButton[playerid], 0);
	PlayerTextDrawAlignment(playerid, LaptopCloseButton[playerid], 2);
	PlayerTextDrawColor(playerid, LaptopCloseButton[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, LaptopCloseButton[playerid], 255);
	PlayerTextDrawBoxColor(playerid, LaptopCloseButton[playerid], -16776961);
	PlayerTextDrawUseBox(playerid, LaptopCloseButton[playerid], 1);
	PlayerTextDrawSetProportional(playerid, LaptopCloseButton[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, LaptopCloseButton[playerid], 1);

    return 1;
}

DestroyLaptopDraw(playerid)
{
    PlayerTextDrawDestroy(playerid, LaptopBackground[playerid]);
	PlayerTextDrawDestroy(playerid, LaptopMonitor[playerid]);
	PlayerTextDrawDestroy(playerid, LaptopMonitorLine[playerid]);
	PlayerTextDrawDestroy(playerid, LaptopVersion[playerid]);
	PlayerTextDrawDestroy(playerid, LaptopCamera[playerid]);
	PlayerTextDrawDestroy(playerid, WarehouseButton[playerid]);
	PlayerTextDrawDestroy(playerid, EBankButton[playerid]);
	PlayerTextDrawDestroy(playerid, AdsListButton[playerid]);
	PlayerTextDrawDestroy(playerid, SpeedTunerButton[playerid]);
	PlayerTextDrawDestroy(playerid, YellowPageButton[playerid]);
	PlayerTextDrawDestroy(playerid, WarehouseIcon[playerid]);
	PlayerTextDrawDestroy(playerid, EBankIcon[playerid]);
	PlayerTextDrawDestroy(playerid, AdsListIcon[playerid]);
	PlayerTextDrawDestroy(playerid, SpeedTunerIcon[playerid]);
	PlayerTextDrawDestroy(playerid, YellowPageIcon[playerid]);
	PlayerTextDrawDestroy(playerid, VehicleImportButton[playerid]);
	PlayerTextDrawDestroy(playerid, FactionImportButton[playerid]);
	PlayerTextDrawDestroy(playerid, FactionImportIcon[playerid]);
	PlayerTextDrawDestroy(playerid, VehicleImportIcon[playerid]);
	PlayerTextDrawDestroy(playerid, LaptopCloseButton[playerid]);
    return 1;
}

OpenLaptop(playerid)
{
    PlayerTextDrawShow(playerid, LaptopBackground[playerid]);
    PlayerTextDrawShow(playerid, LaptopMonitor[playerid]);
    PlayerTextDrawShow(playerid, LaptopMonitorLine[playerid]);
    PlayerTextDrawShow(playerid, LaptopVersion[playerid]);
    PlayerTextDrawShow(playerid, LaptopCamera[playerid]);
    PlayerTextDrawShow(playerid, WarehouseButton[playerid]);
    PlayerTextDrawShow(playerid, EBankButton[playerid]);
    PlayerTextDrawShow(playerid, AdsListButton[playerid]);
    PlayerTextDrawShow(playerid, SpeedTunerButton[playerid]);
    PlayerTextDrawShow(playerid, YellowPageButton[playerid]);
    PlayerTextDrawShow(playerid, WarehouseIcon[playerid]);
    PlayerTextDrawShow(playerid, EBankIcon[playerid]);
    PlayerTextDrawShow(playerid, AdsListIcon[playerid]);
    PlayerTextDrawShow(playerid, SpeedTunerIcon[playerid]);
    PlayerTextDrawShow(playerid, YellowPageIcon[playerid]);
    // PlayerTextDrawShow(playerid, FactionImportButton[playerid]);
    // PlayerTextDrawShow(playerid, FactionImportIcon[playerid]);
    // PlayerTextDrawShow(playerid, VehicleImportButton[playerid]);
    // PlayerTextDrawShow(playerid, VehicleImportIcon[playerid]);
    PlayerTextDrawShow(playerid, LaptopCloseButton[playerid]);
    SelectTextDrawEx(playerid, 0xFF0000FF);
    return 1;
}

CloseLaptop(playerid)
{
    PlayerTextDrawHide(playerid, LaptopBackground[playerid]);
    PlayerTextDrawHide(playerid, LaptopMonitor[playerid]);
    PlayerTextDrawHide(playerid, LaptopMonitorLine[playerid]);
    PlayerTextDrawHide(playerid, LaptopVersion[playerid]);
    PlayerTextDrawHide(playerid, LaptopCamera[playerid]);
    PlayerTextDrawHide(playerid, WarehouseButton[playerid]);
    PlayerTextDrawHide(playerid, EBankButton[playerid]);
    PlayerTextDrawHide(playerid, AdsListButton[playerid]);
    PlayerTextDrawHide(playerid, SpeedTunerButton[playerid]);
    PlayerTextDrawHide(playerid, YellowPageButton[playerid]);
    PlayerTextDrawHide(playerid, WarehouseIcon[playerid]);
    PlayerTextDrawHide(playerid, EBankIcon[playerid]);
    PlayerTextDrawHide(playerid, AdsListIcon[playerid]);
    PlayerTextDrawHide(playerid, SpeedTunerIcon[playerid]);
    PlayerTextDrawHide(playerid, YellowPageIcon[playerid]);
    // PlayerTextDrawHide(playerid, FactionImportButton[playerid]);
    // PlayerTextDrawHide(playerid, FactionImportIcon[playerid]);
    // PlayerTextDrawHide(playerid, VehicleImportButton[playerid]);
    // PlayerTextDrawHide(playerid, VehicleImportIcon[playerid]);
    PlayerTextDrawHide(playerid, LaptopCloseButton[playerid]);
    CancelSelectTextDrawEx(playerid);
    return 1;
}